### ISSUE TITLE
clisp - There is no package with name #1="SLYNK-MACROSTEP"

### ISSUE THREAD

**Issue by repelliuss** [joaotavora/sly-macrostep#5]
I get `SYSTEM::%FIND-PACKAGE: There is no package with name #1="SLYNK-MACROSTEP"` error when I start `sly` with `clisp` implementation. I tried `sbcl`, `ecl` and both work fine.

[Here is the full error.](https://pastebin.com/mR2mFeLb)

Without the `sly-macrostep` package, `sly` works fine with `clisp` too.

SLY 1.0.0-beta-3
GNU Emacs 27.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-09-09
GNU CLISP 2.49.93+

**Comment by George9000** [comment]
Reporting the same issue.

**Comment by George9000** [comment]
Fixed, at least in using doom configuration of Emacs with the  `common-lisp` language option uncommented in the `init` file in `.doom.d` The `config` file also has the line `(setq inferior-lisp-program "/usr/local/bin/clisp")`

That much was done and still giving the error above. What fixed it was installing QuickLisp outside of Emacs.

Quit Emacs.

 Download and install QuickLisp. (see https://exercism.io/tracks/common-lisp/installation)

`curl -O https://beta.quicklisp.org/quicklisp.lisp`

Launch clisp in terminal outside of emacs in the same directory as `quicklisp.lisp` Then, in `clisp`
```
(load "quicklisp.lisp")
(quicklisp-quickstart:install)
(ql:add-to-init-file)
(exit)
```

Restart Emacs. `M-x sly` or editing a lisp file should now start sly/slynk/clisp without an error.

**Comment by joaotavora** [comment]
Though I'm not familiar with Doom or exactly the problem described here, thanks for this recipe!

**Comment by repelliuss** [comment]
I don't think this is a Doom issue but @George9000's solution worked for me too. Thanks!
